### ISSUE TITLE
Reopen for support utf-8 with BOM #115

### ISSUE THREAD

**Issue by bzquan** [terryyin/lizard#116] opened 2016-04-26 05:40 UTC
It still could not manage utf-8 without BOM.

I had followings error messges for utf-08 cpp file WITHOUT BOM.
 Traceback (most recent call last):
 File "C:\Work\BDDTools\QTestRunner\lizard\lizard.py", line 870, in 
 lizard_main(sys.argv)
 File "C:\Work\BDDTools\QTestRunner\lizard\lizard.py", line 864, in lizard_main
 warning_count = printer(result, options, OutputScheme(options.extensions))
 File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext__init__.py", line 10, in print_xml
 print(xml_output(list(results), options.verbose))
 File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext\xmloutput.py", line 21, in xml_output
 root.appendChild(_create_function_measure(doc, result, verbose))
 File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext\xmloutput.py", line 37, in _create_function_measure
 file_name = source_file.filename
 AttributeError: 'NoneType' object has no attribute 'filename'

**Comment by terryyin** [comment] 2016-04-26 05:41
Oops, see. I will look at it tonight my time.

**Comment by terryyin** [comment] 2016-05-01 03:07
Hi @bzquan,
I cannot reproduce the problem. Could you please share a file without BOM with me?

**Comment by bzquan** [comment] 2016-05-01 04:37
Please check the attachment. Please change the extension to cpp.
[NotificationTrace.txt](https://github.com/terryyin/lizard/files/243957/NotificationTrace.txt)

**Comment by terryyin** [comment] 2016-05-01 10:11
I still cannot reproduce it. But from the traceback you provided it should be an encoding problem as you said. Now I made a dirty patch to make it at least not crash in this situation. I don't plan to keep this dirty patch for very long.

Could you please zip the file and send it to me again?

**Comment by bzquan** [comment] 2016-05-01 11:02
Please find the attachment.

[UTF8-no-BOM.zip](https://github.com/terryyin/lizard/files/244071/UTF8-no-BOM.zip)

**Comment by terryyin** [comment] 2016-06-01 06:23
Still cannot reproduce the problem. But I pacified the error when generating XML file.

**Comment by terryyin** [comment] 2016-06-24 14:24
I believe the problem is now properly handled for BOM at least. So I'll close this issue.

**Closed by terryyin** 2016-06-24 14:24 UTC
