### ISSUE TITLE
NLOC is 0 for FileInformation after calling `analyze`

### ISSUE THREAD

**Issue by k0nserv** [terryyin/lizard#274] opened 2019-10-17 13:53 UTC
Hey 👋, 

I've been trying to write a script that uses lizard to analyze some Objective-C code and while CCN seems to be working `NLOC` is always zero for me, but invoking lizard via the CLI or using `analyze_file` reports accurate numbers.

Here's the code I have

```python
import csv
from sys import stdout

from lizard import analyze, analyze_file

EXCLUDE_PATTERN = ['Pods/*']


def collect_results(generator):
    result = []

    for (i, x) in enumerate(generator, 1):
        result.append(x)

        # if i % 1000 == 0:
        #     print(f"Processed {i} files")

    return result


if __name__ == '__main__':
    generator = analyze(
        ["Source/"],
        lans=['objectivec']
    )

    result = collect_results(generator)

    for info in result:
        print(info.__dict__)
        for fun in info.function_list:
            print("{fun.nloc}")

    writer = csv.DictWriter(
        stdout, fieldnames=['filename', 'CCN', 'NLOC', 'avg_tokens']
    )
    writer.writeheader()

    for file_info in result:
        writer.writerow({
            'filename': file_info.filename,
            'CCN': file_info.CCN,
            'NLOC': file_info.nloc,
            'avg_tokens': file_info.average_token_count,
        })
```

Is this a bug or am I making a really simple mistake here?

<details>
<summary>
Environment
</summary>

**Python:** 3.7.4

**pip freeze**
```
entrypoints==0.3
flake8==3.7.8
lizard==1.16.6
mccabe==0.6.1
pycodestyle==2.5.0
pyflakes==2.1.1
```
</details>
</summary>

**Comment by FrancescElies** [comment] 2019-10-18 07:43
I am not sure but I am facing I believe a similar problem, maybe caused by the same issue.

If I download following c file [lz4_decompress.c](https://raw.githubusercontent.com/torvalds/linux/master/lib/lz4/lz4_decompress.c)
and run the following command.
```
python -m lizard --C=1 --ignore_warnings 0 --sort cyclomatic_complexity --html lz4_decompress.c
```

Exit code is always 0, but in the html output I see parts of the code with a higher CCN.


I printed the warning_count in [here](https://mbbm-ast.visualstudio.com/AST/_git/eklang?path=venvlizard/Lib/site-packages/lizard.py&version=GC190687282557112b4022bdf50c16e4d0df5b2f7e&line=1035) and it's zero

**Comment by terryyin** [comment] 2020-01-02 10:02
@k0nserv sorry for the super late reply.

The api you used `analyze` didn't have the default extension list. Everything in lizard is counted using an `extension`. `get_extensions([])` will get the basic list of extensions.

Now I've added it as default if no `exts` are provided. So your code should work fine now.

@FrancescElies I believe you were having a different problem, which is also fixed now.

**Closed by terryyin** 2020-01-02 10:02 UTC

**Comment by k0nserv** [comment] 2020-01-06 16:44
Thanks @terryyin :)
