### ISSUE TITLE
Support utf-8 with BOM

### ISSUE THREAD

**Issue by bzquan** [terryyin/lizard#115] opened 2016-04-23 02:52 UTC
It seems that Lizard could not read source files in utf-8 with BOM.
Would you please support files in utf-8 with BOM?

P.S.
Utf-8 without BOM looks ok.

**Comment by terryyin** [comment] 2016-04-24 01:31
@bzquan yes, I'm working on it. Thanks for reporting.

**Comment by terryyin** [comment] 2016-04-24 03:46
OK. The problem has been fixed. I will include it in a Pypi release in 24 hours.

I believe a big can of worms has just been opened.
It turned out that detecting codecs for text file isn't that easy and there's no perfect way of doing it.
There's a lib (chardet) can do it approximately. So far Lizard doesn't depend on any other Python library. I know it won't be like this for ever, but I don't feel like to introduce chardet this time.
So the current solution is for utf-8 with BOM only. If there's other people request for other codecs, I will continue to do specific patches until a general solution is absolutely needed.

**Comment by bzquan** [comment] 2016-04-24 05:57
Thank you very much. It works.

**Comment by bzquan** [comment] 2016-04-24 06:10
It works for utf-8 with BOM, but it does not work for utf-8 without BOM now.
Windows uses utf-8 with BOM, but Linux uses utf-8 without BOM. I am afraid Lnux users may complain from now on.

**Comment by terryyin** [comment] 2016-04-24 07:20
Oops, @bzquan you are right. The problem is now fixed.

**Comment by bzquan** [comment] 2016-04-24 08:19
Thanks a lot.

**Closed** 2016-04-24 12:25 UTC

**Comment by bzquan** [comment] 2016-04-26 05:37
It still could not manage utf-8 without BOM.
Followings are error messges.
Traceback (most recent call last):
  File "C:\Work\BDDTools\QTestRunner\lizard\lizard.py", line 870, in <module>
    lizard_main(sys.argv)
  File "C:\Work\BDDTools\QTestRunner\lizard\lizard.py", line 864, in lizard_main
    warning_count = printer(result, options, OutputScheme(options.extensions))
  File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext\__init__.py", line 10, in print_xml
    print(xml_output(list(results), options.verbose))
  File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext\xmloutput.py", line 21, in xml_output
    root.appendChild(_create_function_measure(doc, result, verbose))
  File "C:\Work\BDDTools\QTestRunner\lizard\lizard_ext\xmloutput.py", line 37, in _create_function_measure
    file_name = source_file.filename
AttributeError: 'NoneType' object has no attribute 'filename'
