### ISSUE TITLE
Lizard can not generate Html report???

### ISSUE THREAD

**Issue by cyw3** [terryyin/lizard#195] opened 2017-08-15 12:22 UTC
![image](https://user-images.githubusercontent.com/11549103/29315881-13ce0e48-81f8-11e7-88ea-9c1921b31cc0.png)

**Comment by terryyin** [comment] 2017-08-18 07:31
You are right, it's never implemented.

Want to try?

**Comment by rakhimov** [comment] 2017-08-19 23:20
Is this a duplicate of #76?

**Comment by cyw3** [comment] 2017-11-29 04:55
I have implemented Html output by myself.

**Comment by terryyin** [comment] 2017-11-29 06:11
Send a pull request if you like:-)

**Closed** 2018-03-13 03:32 UTC

**Comment by liaogz82** [comment] 2018-03-13 03:42
Err... are you going to create a new release for this? `1.14.0` or something?

**Comment by terryyin** [comment] 2018-03-14 01:51
Will do it by the end of today.

**Comment by terryyin** [comment] 2018-03-14 09:17
Done.
