### ISSUE TITLE
wrong CCN in such situation

### ISSUE THREAD

**Issue by robutcher** [terryyin/lizard#181] opened 2017-04-14 06:15 UTC
xxx.c

typedef struct tagAAA
{

}AAA;

int func_a(int size)
{
    if(ccc() && ddd() && eee())
    {
        return 1;
    }
}

NLOC    Avg.NLOC  AvgCCN  Avg.token  function_cnt    file
--------------------------------------------------------------
     10       7.0     2.0       26.0         1     xxx.c

after  typedef struct tagAAA removed

NLOC    Avg.NLOC  AvgCCN  Avg.token  function_cnt    file
--------------------------------------------------------------
      7       7.0     4.0       26.0         1     xxx.c

**Comment by terryyin** [comment] 2017-04-16 23:32
Hi @robutcher,

Thanks for the report and sorry for the delayed reply. Just had a two week trip. The bug was introduced when adding support for cpp r-value reference. The problem is fixed on the trunk and I will create a new release once I’m reconnected to the internet again.

Terry

**Closed** 2017-04-20 01:17 UTC
