### ISSUE TITLE
Add new counter : max depth of function

### ISSUE THREAD

**Issue by robutcher** [terryyin/lizard#193] opened 2017-08-14 01:38 UTC
would you add a new counter ?
max depth of function

**Comment by rakhimov** [comment] 2017-08-14 01:42
@robutcher C'mon this is a duplicate of your #187 (Why are you opening a duplicate?).
You haven't clarified what 'depth' you want.
All the discussion is in #187.

**Comment by rakhimov** [comment] 2017-08-14 01:46
This is a duplicate of a duplicate : Dupliception :)

**Comment by robutcher** [comment] 2017-08-14 02:09
sorry, I forgot it.

**Closed** 2017-08-14 02:09 UTC
